"""Selectable fabrication-capability profiles (``PNR_FAB_PROFILE``).

One profile is the single source of truth for every fabrication number the
engine uses: the ``rules.json`` ``fab`` block (router grid, native oracles,
KiCad ``.kicad_pro`` board constraints), the electrical/plane-access fab models
(IPC-2221 widths, via-barrel budgets) and the KiCad custom rules
(``<board>.kicad_dru``) that make ``kicad-cli pcb drc`` enforce the PTH / NPTH /
filled-via distinctions KiCad's board constraints cannot express.

Profiles
    ``jlc-pofv`` (default when ``PNR_FAB_PROFILE`` is unset)
        JLCPCB standard 4-layer, 1.6 mm, 1 oz outer / 0.5 oz inner (15.2 um
        finished, stackup JLC04161H-7628) plus epoxy filled & capped vias (POFV)
        on all vias. Values: ``docs/fab-comparison.md`` section 5B on the 5A base;
        each value below cites its row.
    ``legacy``
        The rules as they were before profiles existed. Every function here is
        the identity for it and no ``.kicad_dru`` is written, so
        ``PNR_FAB_PROFILE=legacy`` reproduces the old rules exactly (A/B baseline).

Applied rules carry ``rules['fab_profile'] = <name>`` (never for legacy).
Consuming rules compiled for another profile raises instead of mixing numbers.

Via-in-pad: ``Geometry.in_pad`` (5B filled in-pad class and geometry,
:func:`in_pad_fit` / :func:`in_pad_sites`) and ``Geometry.via_to_smd_pad`` (5A via
copper to SMD pad 0.127) are None for legacy, whose engine keeps its 0.05 mm
via-to-SMD-pad keep-away and never places a via in a pad; pnr.via_in_pad applies
them to native items.
"""
from __future__ import annotations

import copy
import math
import os
import re
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional

ENV = 'PNR_FAB_PROFILE'
DEFAULT = 'jlc-pofv'
LEGACY = 'legacy'
MARKER = 'fab_profile'
DRU_HEADER = '# Generated by pnr.fab_profile'

# The IPC-2221 model's 1 oz is 1.378 mil = 35.0 um finished (pnr.electrical).
OZ_UM = 35.0

# Values the engine hardcoded before profiles (and the old rules.json fab block).
LEGACY_FAB = {
    'track_width_mm': 0.2,
    'clearance_mm': 0.15,
    'via_diameter_mm': 0.6,
    'via_drill_mm': 0.3,
    'hole_clearance_mm': 0.2,
    'edge_clearance_mm': 0.2,
    'min_through_drill_mm': 0.2,
    'via_annular_mm': 0.0,
}

# docs/fab-comparison.md: "5A" = section 5A table row, "5B" = section 5B table row.
_JLC_POFV_FAB = {
    # 5A "Minimum track width": 0.127. The default signal track (track_width_mm)
    # stays the design's 0.20 and is NOT overridden here.
    'min_track_width_mm': 0.127,
    # 5A "Clearance, copper to copper, all layers": 0.127. The engine's routing
    # clearance. Pad-to-pad is the only 0.15 case (next key) and the router never
    # creates pads; KiCad enforces it through the .kicad_dru.
    'clearance_mm': 0.127,
    # 5A "SMD pad to pad, different nets": 0.15 (JLC's own minimum).
    'smd_pad_clearance_mm': 0.15,
    # 5A "Edge clearance, all layers": 0.30 (routed outline, no V-cut).
    'edge_clearance_mm': 0.30,
    # 5A "Hole to edge": 0.50 (PCBWay value; JLC publishes none).
    'hole_to_edge_mm': 0.50,
    # 5A "Via hole to copper": 0.20.
    'hole_clearance_mm': 0.20,
    # 5A "PTH hole to copper": 0.35.
    'pth_hole_clearance_mm': 0.35,
    # 5A "NPTH hole to copper": 0.20.
    'npth_hole_clearance_mm': 0.20,
    # 5A "Hole-to-hole, edge to edge": via to via 0.25 ...
    'hole_to_hole_mm': 0.25,
    # ... any pair involving a component PTH 0.50.
    'pth_hole_to_hole_mm': 0.50,
    # 5B "Filled via hole to any regular PTH or NPTH": 0.45 (all vias are POFV).
    'filled_via_hole_to_hole_mm': 0.45,
    # 5A "Component PTH": hole 0.30 or more. A plated pad hole below it (a
    # footprint's thermal via, e.g. U5.24 / U18.21 at 0.20/0.45 = the 5A escape
    # via) cannot take a component lead; it is a via-class hole (JLC: a via
    # connects layers and is not a soldering hole), drilled and 5B-filled like one,
    # so the via rules apply to it, not the PTH ones (see Geometry.hole_kind).
    'component_pth_min_drill_mm': 0.30,
    # 5A "Via sizes" / 5B "Other via sizes": 0.30/0.45 stays the default.
    'via_diameter_mm': 0.45,
    'via_drill_mm': 0.30,
    # 5B "Via-in-pad via" 0.20/0.35 is the smallest allowed via pad.
    'min_via_diameter_mm': 0.35,
    # 5A "Via drill and ring": minimum drill 0.20, minimum ring 0.075.
    'min_through_drill_mm': 0.20,
    'via_annular_mm': 0.075,
    # 5A "NPTH": 0.50 or more.
    'min_npth_drill_mm': 0.50,
    # 5A "Vias in SMD pads": "Via copper to SMD pad 0.127 or more" (every net,
    # same net included). 5B keeps it for every via that is not a qualified
    # in-pad via (in_pad below); legacy has no key and keeps its 0.05 mm keep-away.
    'via_to_smd_pad_mm': 0.127,
    # Via classes (5A "Via sizes", 5B "Via-in-pad via" / "Other via sizes").
    # in_pad (filled=True) is the via-in-pad policy (Geometry.in_pad, pnr.via_in_pad):
    # a same-net via of this class may sit inside an SMD pad when its hole edge is
    # >= min_hole_edge_to_pad_edge_mm from the pad edge and its copper is inside the
    # pad or it is centred across the pad (5B "Via-in-pad via": 0.20/0.35, centred,
    # hole edge at least 0.09 from the pad edge). alt_diameter_mm is 5B "Alternative
    # if the small-via charge is large" (0.20/0.45, "pad bulges 0.035 per side");
    # row_pitch_mm / min_row_pitch_mm are 5B "Via-in-pad row pitch" (0.50; min 0.45);
    # stagger_mm and remove_unused_inner_pads are 5B "Inner layers" (stagger rows on
    # neighbouring strips of different nets by 0.25; remove unused inner via pads so
    # the In1 antipad is hole + 2 x 0.20 = 0.60).
    'via_classes': {
        'default': {'diameter_mm': 0.45, 'drill_mm': 0.30},
        'escape': {'diameter_mm': 0.45, 'drill_mm': 0.20},
        'in_pad': {'diameter_mm': 0.35, 'drill_mm': 0.20, 'filled': True,
                   'alt_diameter_mm': 0.45,
                   'min_hole_edge_to_pad_edge_mm': 0.09, 'row_pitch_mm': 0.50,
                   'min_row_pitch_mm': 0.45, 'stagger_mm': 0.25,
                   'remove_unused_inner_pads': True},
        'power': {'diameter_mm': 0.60, 'drill_mm': 0.30},
    },
}

# Overlay on the electrical / plane-access fab models (the --electrical-fab and
# --fab-model JSON). Only makes current contracts stricter, never looser.
_JLC_POFV_COPPER = {
    # 5A "Copper model": outer 35 um (1 oz), inner 15.2 um (JLC "0.5 oz"
    # finished), barrel 18 um. inner_copper_oz is the model-equivalent weight of
    # the finished thickness (15.2/35 = 0.434 oz), stricter than nominal 0.5 oz.
    'outer_copper_um': 35.0,
    'inner_copper_um': 15.2,
    'outer_copper_oz': 1.0,
    'inner_copper_oz': 15.2 / OZ_UM,
    # Section 1 (pass 2) / section 3 "20 um via plating assumed": JLC averages 18 um.
    'min_via_plating_um': 18,
    # Default via (5A "Via sizes"); via-array barrels use the default via.
    'via_diameter_mm': 0.45,
    'via_drill_mm': 0.30,
    # Array placement/spacing checks read these from the model (5A/5B rows as above).
    'hole_clearance_mm': 0.20,
    'hole_to_hole_mm': 0.25,
    'pth_hole_to_hole_mm': 0.50,
    'filled_via_hole_to_hole_mm': 0.45,
    'component_pth_min_drill_mm': 0.30,
    'edge_clearance_mm': 0.30,
    'hole_to_edge_mm': 0.50,
    # 5A "Vias in SMD pads": via copper to SMD pad 0.127 (plane-access array barrels).
    'via_to_smd_pad_mm': 0.127,
    'board_thickness_mm': 1.6,
}

_JLC_POFV_QUALIFICATION = (
    'JLCPCB standard 4-layer 1.6 mm (JLC04161H-7628) + POFV screening: 35 um outer / '
    '15.2 um inner finished copper, 18 um barrel plating (docs/fab-comparison.md 5A/5B). '
    'IPC-2221 screening only; IPC-2152 thermal and impedance qualification remain pending.')

PROFILES = {
    LEGACY: None,
    'jlc-pofv': dict(fab=_JLC_POFV_FAB, copper=_JLC_POFV_COPPER,
                     qualification=_JLC_POFV_QUALIFICATION),
}


def active_name(env=None) -> str:
    """The selected profile name (``PNR_FAB_PROFILE``, default jlc-pofv)."""
    name = ((os.environ if env is None else env).get(ENV) or DEFAULT).strip()
    if name not in PROFILES:
        raise ValueError(f'unknown {ENV}={name!r}; expected one of {sorted(PROFILES)}')
    return name


def is_legacy(name: Optional[str] = None) -> bool:
    return (name or active_name()) == LEGACY


def profile_fab(name: Optional[str] = None) -> Dict:
    """The profile's ``fab`` overrides ({} for legacy)."""
    spec = PROFILES[name or active_name()]
    return copy.deepcopy(spec['fab']) if spec else {}


def apply_fab(fab: Optional[Dict], name: Optional[str] = None) -> Dict:
    """``rules['fab']`` with the profile's capability values over it.

    Keys the profile does not define (the design's default ``track_width_mm``)
    pass through. Legacy returns an unchanged copy.
    """
    out = dict(fab or {})
    out.update(profile_fab(name))
    return out


def apply_fab_model(model: Optional[Dict], name: Optional[str] = None) -> Dict:
    """An electrical / plane-access fab model (JSON dict) under the profile.

    Only copper thickness, plating and via geometry change; loss/drop budgets,
    temperature rise and resistivity (the current contracts) are untouched.
    """
    name = name or active_name()
    out = dict(model or {})
    spec = PROFILES[name]
    if not spec:
        return out
    out.update(copy.deepcopy(spec['copper']))
    out['qualification'] = spec['qualification']
    out[MARKER] = name
    return out


def apply_rules(rules: Dict, name: Optional[str] = None) -> Dict:
    """Profile-applied copy of a rules dict (``rules.json`` seam). Idempotent.

    Rewrites ``fab``, ``electrical_fab`` and ``plane_access_fab`` and re-derives
    the current-sized widths / via arrays in ``electrical_nets`` from the new
    copper model. Legacy returns ``rules`` itself, untouched.
    """
    name = name or active_name()
    marker = rules.get(MARKER)
    if marker == name:
        return rules
    if marker is not None:
        raise ValueError(f'rules were compiled for fab profile {marker!r} but {ENV} selects '
                         f'{name!r}; recompile the rules from their sources')
    if name == LEGACY:
        return rules
    out = copy.deepcopy(rules)
    out['fab'] = apply_fab(out.get('fab'), name)
    for key in ('electrical_fab', 'plane_access_fab'):
        if isinstance(out.get(key), dict):
            out[key] = apply_fab_model(out[key], name)
    if isinstance(out.get('electrical_fab'), dict) and out.get('electrical_nets'):
        from pnr.electrical import size_policies
        size_policies(out)
    out[MARKER] = name
    return out


def apply_rules_file(path, name: Optional[str] = None) -> bool:
    """Apply the profile to a rules.json in place. Returns True if rewritten."""
    import json
    path = Path(path)
    rules = json.loads(path.read_text())
    applied = apply_rules(rules, name)
    if applied is rules:
        return False
    path.write_text(json.dumps(applied, indent=2, sort_keys=True))
    return True


# ------------------------------------------------------------------ engine geometry

# Hole kinds (Geometry.hole_kind): the hole a new via must keep its drill gap to.
VIA, PTH, NPTH = 'via', 'pth', 'npth'

# "Centred" across a pad (5B "Via-in-pad via ... centred"): the via centre lies on
# the pad's long-axis centreline within this tolerance (mm, 1 um).
CENTRED_TOL_MM = 1e-3


@dataclass(frozen=True)
class InPad:
    """Filled via-in-pad policy (5B, ``via_classes['in_pad']`` with filled=True).

    ``diameters`` lists the allowed via pads in preference order (5B "Via-in-pad
    via" 0.35 first, then the 5B "Alternative" 0.45); every in-pad via has
    ``drill``. See :func:`in_pad_fit` for the geometry.
    """
    drill: float  # 0.20
    diameters: tuple  # (0.35, 0.45)
    hole_margin: float  # hole edge to pad edge, 0.09
    pitch: float  # row pitch, 0.50
    min_pitch: float  # 0.45
    stagger: Optional[float] = None  # 0.25 against different-net rows on neighbouring strips
    remove_unused_inner_pads: bool = False

    def allows(self, diameter: float, drill: float) -> bool:
        """``diameter``/``drill`` (mm) is an in-pad class via."""
        return abs(drill - self.drill) <= 1e-6 and any(abs(diameter - d) <= 1e-6 for d in self.diameters)


def in_pad_policy(fab: Optional[Dict]) -> Optional[InPad]:
    """The via-in-pad policy of a fab block, or None (legacy / 5A: no via in pads)."""
    spec = ((fab or {}).get('via_classes') or {}).get('in_pad')
    if not isinstance(spec, dict) or not spec.get('filled'):
        return None
    diameters = [float(spec['diameter_mm'])]
    if spec.get('alt_diameter_mm') is not None:
        diameters.append(float(spec['alt_diameter_mm']))
    return InPad(drill=float(spec['drill_mm']), diameters=tuple(diameters),
                 hole_margin=float(spec['min_hole_edge_to_pad_edge_mm']),
                 pitch=float(spec.get('row_pitch_mm', spec['min_row_pitch_mm'])),
                 min_pitch=float(spec.get('min_row_pitch_mm', spec.get('row_pitch_mm'))),
                 stagger=None if spec.get('stagger_mm') is None else float(spec['stagger_mm']),
                 remove_unused_inner_pads=bool(spec.get('remove_unused_inner_pads')))


def _roundrect_sdf(u: float, v: float, hw: float, hh: float, corner: float) -> float:
    """Signed distance (mm, negative inside) of local point (u, v) to a rounded
    rectangle of half extents hw/hh and corner radius ``corner``."""
    corner = max(0.0, min(corner, hw, hh))
    qx, qy = abs(u) - hw + corner, abs(v) - hh + corner
    return math.hypot(max(qx, 0.0), max(qy, 0.0)) + min(max(qx, qy), 0.0) - corner


def in_pad_fit(ip: InPad, size, offset=(0.0, 0.0), diameter: Optional[float] = None,
               drill: Optional[float] = None, corner: Optional[float] = 0.0) -> bool:
    """5B via-in-pad geometry of one via in one pad (mm, pad-local frame).

    ``size`` is the pad (w, h), ``offset`` the via centre relative to the pad centre
    along w and h, ``corner`` the corner radius (0 rectangle; None = unknown, taken
    as the worst case stadium/oval, conservative for every rounded shape). The via
    qualifies when (5B "Via-in-pad via") its hole edge keeps ``hole_margin`` from the
    pad edge and either its copper lies inside the pad or it is centred across the
    pad (5B "centred"; the 0.45 alternative "bulges 0.035 per side" of a 0.38 strip).
    Default diameter/drill: the preferred in-pad class.
    """
    d = ip.diameters[0] if diameter is None else diameter
    h = ip.drill if drill is None else drill
    hw, hh = size[0] / 2, size[1] / 2
    r = min(hw, hh) if corner is None else corner
    sdf = _roundrect_sdf(offset[0], offset[1], hw, hh, r)
    if sdf > -(h / 2 + ip.hole_margin) + 1e-6:
        return False
    if sdf <= -d / 2 + 1e-6:
        return True
    # Centred across the pad: on the long-axis centreline (both axes for a square).
    across = offset[1] if hw >= hh else offset[0]
    along = offset[0] if hw >= hh else offset[1]
    return abs(across) <= CENTRED_TOL_MM and (abs(hw - hh) > CENTRED_TOL_MM or abs(along) <= CENTRED_TOL_MM)


def in_pad_sites(ip: InPad, size, corner: Optional[float] = 0.0, *, pitch: Optional[float] = None,
                 diameter: Optional[float] = None, avoid=(), stagger: Optional[float] = None):
    """Most 5B in-pad vias one pad holds: a centred row along its long axis.

    Returns the via offsets along the long axis (mm, pad centre = 0; the row is on
    the centreline). ``pitch`` defaults to the 5B row pitch (0.50; pass
    ``ip.min_pitch`` for the 0.45 minimum). ``avoid`` holds long-axis offsets of
    different-net vias in neighbouring strips; each site keeps ``stagger`` (default
    the 5B 0.25) from every one of them along the axis.
    """
    pitch = ip.pitch if pitch is None else pitch
    d = ip.diameters[0] if diameter is None else diameter
    long_half = max(size) / 2
    step = .001
    reach = 0.0
    while in_pad_fit(ip, (max(size), min(size)), (reach + step, 0.0), d, ip.drill, corner):
        reach += step
    if not in_pad_fit(ip, (max(size), min(size)), (0.0, 0.0), d, ip.drill, corner):
        return []
    reach = min(reach, long_half)
    gap = (ip.stagger if stagger is None else stagger) if avoid else 0.0
    ok = lambda u: all(abs(u - a) >= gap - 1e-9 for a in avoid)
    # Unconstrained: the symmetric centred row.
    n = int(math.floor(2 * reach / pitch + 1e-9)) + 1
    row = [round((i - (n - 1) / 2) * pitch, 6) for i in range(n)]
    if all(ok(u) for u in row):
        return row
    # With stagger: earliest-first placement from every start phase (1 um lattice)
    # finds the most sites; ties keep the most centred row.
    best = []
    ticks = int(round(2 * reach / step))
    u_values = [round(-reach + k * step, 6) for k in range(ticks + 1)]
    for first in u_values:
        if not ok(first):
            continue
        placed = [first]
        for u in u_values:
            if u >= placed[-1] + pitch - 1e-9 and ok(u):
                placed.append(u)
        if (len(placed), -abs(sum(placed))) > (len(best), -abs(sum(best))):
            best = placed
        if first > -reach + pitch:
            break
    return best


@dataclass(frozen=True)
class Geometry:
    """Fab numbers the engine's own geometry checks use (mm).

    Optional distinctions are None when the profile does not make them (legacy),
    in which case callers keep their old single-value behaviour exactly. The
    derived values (``via_radius``, ``hole_gap``, ``same_net_via_pitch``,
    ``clearance_gap``, ``edge_gap``, ``max_via_hole_gap``) are plain attributes
    computed once: the regional solvers read them per primitive pair.
    """
    via_diameter: float
    via_drill: float
    clearance: float
    hole_clearance: float  # via hole to copper
    hole_to_hole: float  # via to via, drill edge to drill edge
    edge_clearance: float
    pth_hole_clearance: Optional[float] = None
    npth_hole_clearance: Optional[float] = None
    pth_hole_to_hole: Optional[float] = None
    filled_via_hole_to_hole: Optional[float] = None
    hole_to_edge: Optional[float] = None
    component_pth_min_drill: Optional[float] = None
    # Via copper to any SMD pad (5A 0.127) and the filled via-in-pad policy (5B);
    # None (legacy): the pre-profile 0.05 mm via-to-SMD-pad keep-away, no via in pads.
    via_to_smd_pad: Optional[float] = None
    in_pad: Optional[InPad] = None

    def __post_init__(self):
        derived = dict(
            # Default via radius (legacy 0.3).
            via_radius=round(self.via_diameter / 2, 9),
            # Via-to-via drill gap plus the engine's 1 um margin (legacy 0.201).
            hole_gap=round(self.hole_to_hole + .001, 9),
            # Minimum centre distance of two distinct default-via drills (legacy 0.501).
            same_net_via_pitch=round(self.via_drill + self.hole_to_hole + .001, 9),
            # Copper clearance plus the 1 um margin (legacy 0.151).
            clearance_gap=round(self.clearance + .001, 9),
            # Copper-to-edge clearance plus the 1 um margin (legacy 0.201).
            edge_gap=round(self.edge_clearance + .001, 9))
        for key, value in derived.items():
            object.__setattr__(self, key, value)
        # Largest drill gap a new via needs to any existing hole.
        object.__setattr__(self, 'max_via_hole_gap',
                           max(self.via_hole_gap(PTH), self.via_hole_gap(NPTH), self.hole_to_hole))

    def hole_kind(self, is_via: bool, plated: Optional[bool] = None, drill: float = 0.0) -> Optional[str]:
        """Kind of an existing hole: VIA, PTH (component PTH), NPTH, or None
        (a pad whose plating is unknown).

        ``drill`` is the pad hole's larger dimension (mm). A plated pad hole under
        ``component_pth_min_drill`` (5A "Component PTH: hole 0.30 or more") is a
        footprint's via (thermal / stitching, e.g. 0.20/0.45): it takes no lead,
        is drilled and filled like a via and gets the via rules. Without the
        distinction (legacy) every plated pad is PTH.
        """
        if is_via:
            return VIA
        if plated is None:
            return None
        if not plated:
            return NPTH
        if self.component_pth_min_drill is not None and drill < self.component_pth_min_drill - 1e-9:
            return VIA
        return PTH

    def via_hole_gap(self, kind: Optional[str] = VIA) -> float:
        """Drill edge gap from a new via hole to an existing hole of ``kind``
        (:meth:`hole_kind`; None = a pad of unknown plating: the strictest pad value)."""
        if kind == VIA:
            return self.hole_to_hole
        pth = self.pth_hole_to_hole if self.pth_hole_to_hole is not None else self.hole_to_hole
        npth = (self.filled_via_hole_to_hole if self.filled_via_hole_to_hole is not None
                else self.hole_to_hole)
        return pth if kind == PTH else npth if kind == NPTH else max(pth, npth)

    def pad_hole_clearance(self, kind: Optional[str]) -> Optional[float]:
        """Hole-to-foreign-copper keep-out the engine adds around a pad's drill,
        or None where the pre-profile model adds none (plated pads under legacy,
        whose copper land is the obstacle). NPTH: its own value (legacy 0.20)."""
        if kind == NPTH:
            return self.npth_hole_clearance if self.npth_hole_clearance is not None else self.hole_clearance
        if self.pth_hole_clearance is None:
            return None
        return self.pth_hole_clearance if kind in (PTH, None) else self.hole_clearance

    def via_edge_margin(self, diameter: Optional[float] = None, drill: Optional[float] = None) -> float:
        """Via centre to board edge incl. the 1 um margin: copper edge clearance
        and, when the profile has one, hole-to-edge (legacy 0.6 via: 0.501)."""
        d = self.via_diameter if diameter is None else diameter
        h = self.via_drill if drill is None else drill
        margin = d / 2 + self.edge_gap
        if self.hole_to_edge is not None:
            margin = max(margin, h / 2 + round(self.hole_to_edge + .001, 9))
        return margin


def geometry(rules: Optional[Dict] = None, name: Optional[str] = None) -> Geometry:
    """Engine geometry from a rules dict, else (``rules is None``) from the profile.

    Code holding rules reads only the rules (profile-applied at the pipeline
    boundaries), so a legacy rules dict keeps legacy geometry whatever the env.
    """
    if rules is not None:
        fab = dict(LEGACY_FAB)
        fab.update(rules.get('fab') or {})
    else:
        fab = apply_fab(LEGACY_FAB, name)
    f = lambda key: None if fab.get(key) is None else float(fab[key])
    hole = float(fab['hole_clearance_mm'])
    return Geometry(
        via_diameter=float(fab['via_diameter_mm']), via_drill=float(fab['via_drill_mm']),
        clearance=float(fab['clearance_mm']), hole_clearance=hole,
        hole_to_hole=f('hole_to_hole_mm') if f('hole_to_hole_mm') is not None else hole,
        edge_clearance=float(fab['edge_clearance_mm']),
        pth_hole_clearance=f('pth_hole_clearance_mm'), npth_hole_clearance=f('npth_hole_clearance_mm'),
        pth_hole_to_hole=f('pth_hole_to_hole_mm'), filled_via_hole_to_hole=f('filled_via_hole_to_hole_mm'),
        hole_to_edge=f('hole_to_edge_mm'), component_pth_min_drill=f('component_pth_min_drill_mm'),
        via_to_smd_pad=f('via_to_smd_pad_mm'), in_pad=in_pad_policy(fab))


# The process's profile geometry. PNR_FAB_PROFILE is read once, on first use, not
# per call (os.environ lookups dominated the regional solvers' hot paths); the
# pipeline selects the profile before a process starts and never changes it.
_ACTIVE: Optional[Geometry] = None
_BINDINGS = []


def active_geometry() -> Geometry:
    """Profile geometry for rule-less code (regional solvers), fixed per process.

    Hot paths should not call this per primitive: hoist it out of loops, or keep
    the numbers in module globals through :func:`bind_active`.
    """
    global _ACTIVE
    g = _ACTIVE
    if g is None:
        g = _ACTIVE = geometry(name=active_name())
    return g


def bind_active(callback) -> None:
    """Call ``callback(active_geometry())`` now and after every :func:`reset_active`.

    For modules that keep profile numbers in module globals, so their per-pair
    code reads them as cheaply as the literals they replaced.
    """
    _BINDINGS.append(callback)
    callback(active_geometry())


def reset_active() -> Geometry:
    """Re-read PNR_FAB_PROFILE and rebind (tests / in-process profile switches).

    An unknown profile raises, as everywhere else, and leaves the previous
    geometry bound.
    """
    global _ACTIVE
    g = geometry(name=active_name())
    _ACTIVE = g
    for callback in _BINDINGS:
        callback(g)
    return g


# ------------------------------------------------------------------ KiCad enforcement

def board_constraints(fab: Dict) -> Dict:
    """``.kicad_pro`` board.design_settings.rules for a fab block.

    Keys absent from ``fab`` fall back exactly to the pre-profile mapping.
    """
    return {
        'min_clearance': fab['clearance_mm'],
        'min_track_width': fab.get('min_track_width_mm', fab['track_width_mm']),
        'min_via_diameter': fab.get('min_via_diameter_mm', fab['via_diameter_mm']),
        'min_via_annular_width': fab['via_annular_mm'],
        'min_through_hole_diameter': fab['min_through_drill_mm'],
        'min_hole_clearance': fab['hole_clearance_mm'],
        'min_hole_to_hole': fab.get('hole_to_hole_mm', fab['hole_clearance_mm']),
        'min_copper_edge_clearance': fab['edge_clearance_mm'],
    }


def _mm(value: float) -> str:
    return ('%.4f' % value).rstrip('0').rstrip('.') + 'mm'


def dru_text(fab: Optional[Dict] = None, name: Optional[str] = None,
             netclass_clearances: Optional[Dict[str, float]] = None,
             edge_stroke_mm: float = 0.0) -> Optional[str]:
    """KiCad 10 custom rules for the profile; None when it has none (legacy).

    Semantics verified with kicad-cli 10.0.6 on a probe board:
    * two-item conditions are tried in both (A, B) orders;
    * a matching custom ``clearance`` rule REPLACES the netclass clearance (it
      can weaken it), so the SMD pad rule excludes every netclass whose own
      clearance exceeds it (``netclass_clearances``: name -> mm);
    * of several matching rules of one constraint type the later one wins, so
      stricter overlapping rules are written later;
    * ``physical_hole_clearance`` against Edge.Cuts measures the drill wall to
      the outline *stroke edge*, whereas ``edge_clearance`` (copper) and the
      engine (``outline_bounds``) measure to the outline centreline, which is
      what the fab routes. The rule is therefore reduced by half the board's
      widest Edge.Cuts stroke (``edge_stroke_mm``) so all three agree;
    * a plated pad hole under ``component_pth_min_drill_mm`` (a footprint's
      thermal via) is a via-class hole (:meth:`Geometry.hole_kind`): the via
      rules apply to it, not the component-PTH ones. ``Hole_Size_X/Y`` are the
      pad drill's dimensions, so a slot is a component PTH if either reaches it;
    * ``physical_clearance`` is checked between same-net items too (a via inside
      a pad reports its copper distance to the pad edge), and ``A.Hole`` is a
      via's drill: the via-to-SMD-pad rule exempts only the 0.20-drill in-pad
      class, whose 5B geometry (hole edge 0.09 from the pad edge, centred) no
      KiCad rule expresses and pnr.via_in_pad checks.
    """
    name = name or active_name()
    if is_legacy(name):
        return None
    f = apply_fab(fab if fab is not None else LEGACY_FAB, name)
    smd = f['smd_pad_clearance_mm']
    d = _mm(f['component_pth_min_drill_mm'])

    def kinds(x):
        """Conditions on item ``x`` (A or B): via-class hole, component PTH, NPTH."""
        plated = f"{x}.Type == 'Pad' && {x}.Pad_Type == 'Through-hole'"
        via = f"({x}.Type == 'Via' || ({plated} && {x}.Hole_Size_X < {d} && {x}.Hole_Size_Y < {d}))"
        pth = f"({plated} && ({x}.Hole_Size_X >= {d} || {x}.Hole_Size_Y >= {d}))"
        npth = f"({x}.Type == 'Pad' && {x}.Pad_Type == 'NPTH, mechanical')"
        return via, pth, npth
    via_a, pth_a, npth_a = kinds('A')
    via_b, pth_b, npth_b = kinds('B')
    wider = sorted(n for n, c in (netclass_clearances or {}).items() if c is not None and c > smd + 1e-9)
    keep = ''.join(f" && A.NetClass != '{n}' && B.NetClass != '{n}'" for n in wider)
    in_pad = in_pad_policy(f)
    rules = [
        ('smd_pad_to_pad', "A.Type == 'Pad' && B.Type == 'Pad' && A.Pad_Type == 'SMD' && B.Pad_Type == 'SMD'" + keep,
         'clearance', smd, '5A SMD pad to pad, different nets (clearance applies to different nets only)'),
    ]
    if f.get('via_to_smd_pad_mm') is not None:
        # physical_clearance applies to same-net items too (kicad-cli 10.0.6 probe).
        # A via overlapping or entering a pad reports its copper distance to the pad
        # edge, so only the in-pad class (drill 0.20; A.Hole is the via drill) is
        # exempt: KiCad cannot express the 5B in-pad geometry (hole edge 0.09 from
        # the pad edge, centred), which pnr.via_in_pad checks for those vias.
        exempt = f" && A.Hole > {_mm(in_pad.drill)}" if in_pad else ''
        rules.append(('via_to_smd_pad', f"A.Type == 'Via'{exempt} && B.Type == 'Pad' && B.Pad_Type == 'SMD'",
                      'physical_clearance', f['via_to_smd_pad_mm'],
                      '5A Vias in SMD pads: via copper to SMD pad 0.127 (any net); 5B Via-in-pad via: '
                      'only the filled 0.20-drill in-pad class may enter an SMD pad'))
    rules += [
        ('via_hole_clearance', via_a, 'hole_clearance', f['hole_clearance_mm'],
         '5A Via hole to copper (vias and via-class footprint holes under 5A Component PTH hole 0.30)'),
        ('npth_hole_clearance', npth_a, 'hole_clearance', f['npth_hole_clearance_mm'],
         '5A NPTH hole to copper'),
        # Via-class holes are excluded (either order): their hole is 5A "Via hole
        # to copper", and PTH hole to via copper is already >= 0.35 through the 0.50
        # hole-to-hole rule for every via class ring (<= 0.15).
        ('pth_hole_clearance', f'{pth_a} && !{via_b}', 'hole_clearance', f['pth_hole_clearance_mm'],
         '5A PTH hole to copper (component PTH: 5A hole 0.30 or more)'),
        ('via_hole_to_hole', f'{via_a} && {via_b}', 'hole_to_hole', f['hole_to_hole_mm'],
         '5A Hole-to-hole, via to via'),
        ('filled_via_to_pad_hole', f'{via_a} && ({pth_b} || {npth_b})', 'hole_to_hole',
         f['filled_via_hole_to_hole_mm'], '5B Filled via hole to any regular PTH or NPTH'),
        ('component_pth_hole_to_hole', pth_a, 'hole_to_hole', f['pth_hole_to_hole_mm'],
         '5A Hole-to-hole, any pair involving a component PTH'),
        ('npth_min_drill', npth_a, 'hole_size', f['min_npth_drill_mm'], '5A NPTH 0.50 or more'),
        ('hole_to_edge', "A.Layer == 'Edge.Cuts' || B.Layer == 'Edge.Cuts'", 'physical_hole_clearance',
         max(0.0, f['hole_to_edge_mm'] - edge_stroke_mm / 2),
         f'5A Hole to edge {_mm(f["hole_to_edge_mm"])} to the outline centreline '
         f'(KiCad measures to the stroke edge: minus half the {_mm(edge_stroke_mm)} Edge.Cuts stroke)'),
    ]
    lines = ['(version 1)',
             f'{DRU_HEADER} (profile {name}); docs/fab-comparison.md 5A/5B.',
             '# Rewritten on every project stamp and native DRC: edit pnr/fab_profile.py.']
    for rule, condition, kind, value, source in rules:
        lines += [f'# {source}', f'(rule "{name}_{rule}"',
                  f'  (constraint {kind} (min {_mm(value)}))', f'  (condition "{condition}"))']
    return '\n'.join(lines) + '\n'


def project_netclass_clearances(project) -> Dict[str, float]:
    """Netclass name -> clearance from a ``.kicad_pro`` ({} if unreadable)."""
    import json
    try:
        pro = json.loads(Path(project).with_suffix('.kicad_pro').read_text())
    except (OSError, ValueError):
        return {}
    classes = (pro.get('net_settings') or {}).get('classes') or []
    return {c['name']: c.get('clearance') for c in classes if isinstance(c, dict) and 'name' in c}


_EDGE_STROKE = re.compile(r'\(stroke\s*\(width\s+([\d.]+)\)\s*\(type\s+\w+\)\s*\)\s*'
                          r'(?:\(fill\s+[^()]*\)\s*)?\(layer\s+"Edge\.Cuts"\)')


def edge_stroke_width(board_or_project) -> float:
    """Widest Edge.Cuts stroke (mm) in the board file, 0.0 if unknown."""
    try:
        text = Path(board_or_project).with_suffix('.kicad_pcb').read_text()
    except OSError:
        return 0.0
    return max((float(w) for w in _EDGE_STROKE.findall(text)), default=0.0)


def dru_path(board_or_project) -> Path:
    return Path(board_or_project).with_suffix('.kicad_dru')


def write_dru(board_or_project, fab: Optional[Dict] = None, name: Optional[str] = None) -> Optional[Path]:
    """Write (or, for legacy, remove a stale generated) ``<stem>.kicad_dru``.

    Only files carrying :data:`DRU_HEADER` are ever replaced or removed. A
    hand-written .kicad_dru is never touched: KiCad reads one rules file per
    project, so the profile's custom rules are then NOT applied (warned on
    stderr); its board constraints in the .kicad_pro still are.
    """
    path = dru_path(board_or_project)
    text = None if is_legacy(name) else dru_text(fab, name, project_netclass_clearances(path),
                                                  edge_stroke_width(path))
    existing = path.read_text() if path.exists() else None
    if existing is not None and DRU_HEADER not in existing:
        if text is not None:
            import sys
            print(f'pnr.fab_profile: {path} is hand-written; {name or active_name()} custom rules '
                  'not applied', file=sys.stderr)
        return None
    if text is None:
        if existing is not None:
            path.unlink()
        return None
    if existing != text:
        # Unique temporary: parallel workers may write the same board's file.
        tmp = path.with_name(f'.{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp')
        tmp.write_text(text)
        os.replace(tmp, path)
    return path


def copy_dru(source_board, target_board) -> Optional[Path]:
    """Carry ``<source>.kicad_dru`` to ``<target>.kicad_dru`` beside a copied
    ``.kicad_pro`` (the custom rules travel with the project). Returns the
    target, or None when the source has no rules file."""
    import shutil
    source, target = dru_path(source_board), dru_path(target_board)
    if not source.exists():
        return None
    if source.resolve() != target.resolve():
        shutil.copyfile(source, target)
    return target


def load_board(path):
    """``pcbnew.LoadBoard`` with the profile's custom rules in force.

    KiCad builds a loaded board's DRC engine, whose rules the zone filler also
    applies, from ``<stem>.kicad_dru`` *at load time*. A board loaded without it
    refills zones to the netclass / board minimums only (a component PTH hole
    gets 0.20 instead of 0.35), and the native DRC that follows, which does
    have the rules, rejects that copper. Every tool that refills zones loads
    its board through here. Legacy writes nothing (it removes only a stale
    generated file), so its fills are unchanged.
    """
    import pcbnew
    if Path(path).is_file():
        write_dru(path)
    return pcbnew.LoadBoard(str(path))
