"""Filling a part cache from existing part directories and picker catalogs.

Used to move a project's committed parts out of its repository and into a cache (for example
Splanc's boards; docs/part-cache.md, "Importing parts"). Provenance is taken from what the files
say about themselves: a part whose ``.ato`` carries atopile's ``is_auto_generated`` trait is
recorded with that trait's source (``easyeda:C<id>``) and date; a part without it as hand-authored
or hand-edited. The licence is recorded as ``NOASSERTION`` with a note, because the cache cannot
know more than the files and the importer's ``--licence-note`` say.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from yapnr.frontends.atopile.picker import catalog as catalog_mod
from yapnr.partcache import model
from yapnr.partcache.client import PartCache, read_part_dir

EASYEDA_TERMS = "https://easyeda.com/page/legal"


def provenance_for(
    part_dir: Path, imported_from: str, notes: Optional[str] = None
) -> Dict[str, str]:
    name = Path(part_dir).name
    facts = model.ato_facts(name, (Path(part_dir) / f"{name}.ato").read_text(encoding="utf-8"))
    provenance = {"imported_from": imported_from}
    if facts["generated_from"]:
        provenance["source"] = facts["generated_from"]
        provenance["generator"] = "atopile ato create part (is_auto_generated)"
        if facts["generated_at"]:
            provenance["created"] = facts["generated_at"]
    else:
        provenance["source"] = "hand-authored or hand-edited (no is_auto_generated trait)"
    if notes:
        provenance["notes"] = notes
    return provenance


def licence_for(
    provenance: Dict[str, str], note: Optional[str] = None, local_only: bool = False
) -> Dict[str, str]:
    source = provenance.get("source", "")
    if source.startswith("easyeda:"):
        licence = {
            "spdx": "NOASSERTION",
            "notes": "Footprint, symbol and 3D model generated by atopile from EasyEDA/LCSC"
            " library data for this part; the source's terms apply.",
            "terms_url": EASYEDA_TERMS,
        }
    else:
        licence = {
            "spdx": "NOASSERTION",
            "notes": "Part files authored or edited by hand; they may derive from generated data.",
        }
    if note:
        licence["notes"] = f"{licence['notes']} {note}"
    if local_only:
        licence["distribution"] = model.LOCAL_ONLY
    return licence


def import_part_dirs(
    cache: PartCache,
    part_dirs: Iterable[Path],
    imported_from: str,
    licence_note: Optional[str] = None,
    notes: Optional[str] = None,
    local_only: bool = False,
) -> List[Dict[str, Any]]:
    """Upload each part directory; returns one record per part (name, id, lcsc, source).

    ``local_only`` marks the parts ``licence.distribution: local-only`` (files that must not
    leave this machine, such as a manufacturer's model under restrictive terms).

    Raises ImportFailed, after importing every other part, when some parts are refused.
    """
    results, failures = [], []
    for part_dir in part_dirs:
        part_dir = Path(part_dir)
        try:
            provenance = provenance_for(part_dir, f"{imported_from}/{part_dir.name}", notes)
            licence = licence_for(provenance, licence_note, local_only=local_only)
            request, blobs = read_part_dir(part_dir, provenance, licence)
            before = model.part_id(request["name"], request["files"])
            manifest = cache.upload_part(request, blobs)
        except (model.InvalidPart, OSError, UnicodeDecodeError) as err:
            failures.append((part_dir.name, str(err)))
            continue
        if manifest["id"] != before:
            raise RuntimeError(f"{part_dir}: the cache stored {manifest['id']}, expected {before}")
        results.append(
            {
                "name": manifest["name"],
                "id": manifest["id"],
                "lcsc": manifest.get("lcsc"),
                "source": provenance["source"],
                "warnings": manifest.get("warnings", []),
            }
        )
    if failures:
        raise ImportFailed(results, failures)
    return results


class ImportFailed(Exception):
    """Some part directories were refused; ``imported`` holds the others."""

    def __init__(self, imported: List[Dict[str, Any]], failures: List[Any]):
        super().__init__(
            f"{len(failures)} parts refused: " + "; ".join(f"{n}: {e}" for n, e in failures)
        )
        self.imported = imported
        self.failures = failures


def part_dirs_under(parts_root: Path) -> List[Path]:
    """The atopile part directories (``<name>/<name>.ato``) directly under ``parts_root``."""
    return sorted(
        d for d in Path(parts_root).iterdir() if d.is_dir() and (d / f"{d.name}.ato").is_file()
    )


def import_catalog(
    cache: PartCache, doc: Dict[str, Any], only: Optional[Iterable[str]] = None
) -> int:
    """Store each part of a validated catalog as a catalog entry (optionally only ``only``)."""
    wanted = {catalog_mod.normalize_lcsc(x) for x in only} if only is not None else None
    count = 0
    for part in doc["parts"]:
        if wanted is not None and part["lcsc"] not in wanted:
            continue
        cache.put_catalog(part, doc["provenance"])
        count += 1
    return count


def today() -> str:
    return _dt.date.today().isoformat()
