"""The material grid: design variables → the density of every design pixel (design §7.1).

The design window is a 2D grid of pixels on the copper plane, index (i, j) with i along x and
j along y. Pixels are either

- **fixed** (port pads, keepouts, element pads): their value is given and they carry no design
  variable (MMA bounds lb = ub in the design's words; here they are simply left out of x), or
- **free**: each belongs to one design variable. With mirror symmetry the pixels of one orbit of
  the mirror group share a variable ("half the DOF"), so the design is symmetric and stays
  binary when projected (the paper averages mirrored material grids instead, which makes
  asymmetric binary designs gray).

Around the window an **exterior ring** of `ring_width` pixels holds fixed values (1 on the
feeds that enter the window, 0 elsewhere), so the filter sees the feeds continue instead of
edge-replicated values.

Mirror conventions: "x" reflects i → ni − 1 − i (mirror about the vertical centre line,
x → −x), "y" reflects j → nj − 1 − j (mirror about the horizontal centre line, y → −y).
"""

from __future__ import annotations

import numpy as np

SYMMETRIES = {
    "none": (),
    "mirror_x": ("x",),
    "mirror_y": ("y",),
    "mirror_xy": ("x", "y"),
}


def _mirror(a: np.ndarray, axes) -> np.ndarray:
    for ax in axes:
        a = np.flip(a, axis={"x": 0, "y": 1}[ax])
    return a


def _group(axes) -> list[tuple[str, ...]]:
    """The mirror group generated by `axes`: every subset of the reflections."""
    out = [()]
    for ax in axes:
        out = out + [g + (ax,) for g in out]
    return out


class MaterialGrid:
    """The design window's pixels, fixed values, symmetry and exterior ring.

    Args:
      shape: (ni, nj) pixels of the design window.
      fixed: bool (ni, nj), True where the pixel value is fixed.
      fixed_value: float (ni, nj), the values of fixed pixels (ignored elsewhere).
      ring: float (ni + 2r, nj + 2r), the values around the window (the inner part is
        ignored), or None for zeros.
      ring_width: r, the ring width in pixels.
      symmetry: a key of `SYMMETRIES` or a tuple of mirror axes ("x", "y").
    """

    def __init__(
        self,
        shape: tuple[int, int],
        *,
        fixed: np.ndarray | None = None,
        fixed_value: np.ndarray | None = None,
        ring: np.ndarray | None = None,
        ring_width: int = 0,
        symmetry="none",
    ):
        ni, nj = (int(shape[0]), int(shape[1]))
        if ni < 1 or nj < 1:
            raise ValueError("the design window needs at least one pixel")
        self.shape = (ni, nj)
        self.fixed = np.zeros(self.shape, bool) if fixed is None else np.asarray(fixed, bool)
        self.fixed_value = (
            np.zeros(self.shape) if fixed_value is None else np.asarray(fixed_value, np.float64)
        )
        if self.fixed.shape != self.shape or self.fixed_value.shape != self.shape:
            raise ValueError("fixed and fixed_value must have the window's shape")
        self.fixed_value = np.where(self.fixed, self.fixed_value, 0.0)
        r = int(ring_width)
        self.ring_width = r
        ext_shape = (ni + 2 * r, nj + 2 * r)
        self.ring = np.zeros(ext_shape) if ring is None else np.asarray(ring, np.float64).copy()
        if self.ring.shape != ext_shape:
            raise ValueError(f"ring must have shape {ext_shape}, got {self.ring.shape}")
        self.ring[r : r + ni, r : r + nj] = 0.0
        self.symmetry = tuple(SYMMETRIES[symmetry]) if isinstance(symmetry, str) else symmetry
        for ax in self.symmetry:
            if ax not in ("x", "y"):
                raise ValueError(f"unknown mirror axis {ax!r}")
        self._check_symmetric()
        self._number_dof()

    # -- setup ----------------------------------------------------------------------------------

    def _check_symmetric(self) -> None:
        if not self.symmetry:
            return
        for g in _group(self.symmetry)[1:]:
            if not np.array_equal(_mirror(self.fixed, g), self.fixed):
                raise ValueError(f"fixed pixels are not symmetric under mirror {g}")
            if not np.allclose(_mirror(self.fixed_value, g), self.fixed_value):
                raise ValueError(f"fixed values are not symmetric under mirror {g}")
            if not np.allclose(_mirror(self.ring, g), self.ring):
                raise ValueError(f"the exterior ring is not symmetric under mirror {g}")

    def _number_dof(self) -> None:
        """Number the orbits of free pixels in row-major order of their first pixel."""
        ni, nj = self.shape
        flat = np.arange(ni * nj).reshape(self.shape)
        rep = flat.copy()
        for g in _group(self.symmetry)[1:]:
            rep = np.minimum(rep, _mirror(flat, g))
        rep = np.where(self.fixed, -1, rep)
        reps = np.unique(rep[rep >= 0])
        index = np.full(self.shape, -1, dtype=np.int64)
        pos = np.searchsorted(reps, rep[rep >= 0])
        index[rep >= 0] = pos
        self.dof_index = index
        self.n_dof = int(reps.size)
        self.orbit_size = np.bincount(index[index >= 0], minlength=self.n_dof).astype(np.float64)

    # -- maps -----------------------------------------------------------------------------------

    @property
    def free(self) -> np.ndarray:
        return ~self.fixed

    def initial(self, value: float = 0.5) -> np.ndarray:
        """A uniform design x (n_dof,)."""
        return np.full(self.n_dof, float(value))

    def embed(self, x):
        """ρ (ni, nj): x on the free pixels, the fixed values elsewhere (numpy or torch)."""
        if isinstance(x, np.ndarray):
            rho = self.fixed_value.copy()
            rho[self.free] = x[self.dof_index[self.free]]
            return rho
        import torch

        idx = torch.as_tensor(np.where(self.fixed, 0, self.dof_index).ravel())
        vals = x.index_select(0, idx).reshape(self.shape)
        fixed = torch.as_tensor(self.fixed)
        return torch.where(fixed, torch.as_tensor(self.fixed_value, dtype=x.dtype), vals)

    def embed_transpose(self, g: np.ndarray) -> np.ndarray:
        """Transpose of `embed`'s linear part: per-pixel gradients (..., ni, nj) → (..., n_dof)."""
        g = np.asarray(g, dtype=np.float64)
        lead = g.shape[:-2]
        flat = g.reshape(lead + (-1,))[..., self.free.ravel()]
        idx = self.dof_index[self.free]
        out = np.zeros(lead + (self.n_dof,))
        for k in np.ndindex(*lead) if lead else [()]:
            out[k] = np.bincount(idx, weights=flat[k], minlength=self.n_dof)
        return out

    def restrict(self, rho: np.ndarray) -> np.ndarray:
        """x from a pixel field: the mean of ρ over each orbit of free pixels."""
        rho = np.asarray(rho, dtype=np.float64)
        idx = self.dof_index[self.free]
        return np.bincount(idx, weights=rho[self.free], minlength=self.n_dof) / self.orbit_size

    def extend(self, rho):
        """ρ_ext (ni + 2r, nj + 2r): the window inside the fixed ring (numpy or torch)."""
        r = self.ring_width
        ni, nj = self.shape
        if isinstance(rho, np.ndarray):
            ext = self.ring.copy()
            ext[r : r + ni, r : r + nj] = rho
            return ext
        import torch

        ext = torch.as_tensor(self.ring, dtype=rho.dtype).clone()
        ext[r : r + ni, r : r + nj] = rho
        return ext

    def reimpose(self, rho_bar):
        """ρ̄ with the fixed pixels set back to their values (after the projection)."""
        if isinstance(rho_bar, np.ndarray):
            return np.where(self.fixed, self.fixed_value, rho_bar)
        import torch

        return torch.where(
            torch.as_tensor(self.fixed),
            torch.as_tensor(self.fixed_value, dtype=rho_bar.dtype),
            rho_bar,
        )

    # -- serialization --------------------------------------------------------------------------

    def to_json(self) -> dict:
        return {
            "shape": list(self.shape),
            "ring_width": self.ring_width,
            "symmetry": list(self.symmetry),
            "n_dof": self.n_dof,
            "fixed_pixels": int(self.fixed.sum()),
        }
