"""The atopile toolchain: the interpreter of a discovered atopile environment (repo.bzl)."""

AtopileToolchainInfo = provider(
    doc = "An atopile environment outside Bazel, and the headless KiCad next to it.",
    fields = {
        "available": "True when an environment with the pinned atopile was found.",
        "python": "Absolute path of the environment's Python interpreter.",
        "version": "The atopile version found.",
        "source": "Where the environment was found (the discovery step).",
        "reason": "Why none was found, when `available` is False.",
        "kicad_cli": "The headless kicad-cli, or empty.",
        "kicad_footprints": "KiCad's stock footprint directory, or empty.",
    },
)

def _atopile_toolchain_impl(ctx):
    info = AtopileToolchainInfo(
        available = ctx.attr.available,
        python = ctx.attr.python,
        version = ctx.attr.version,
        source = ctx.attr.source,
        reason = ctx.attr.reason,
        kicad_cli = ctx.attr.kicad_cli,
        kicad_footprints = ctx.attr.kicad_footprints,
    )
    return [platform_common.ToolchainInfo(atopile = info)]

atopile_toolchain = rule(
    implementation = _atopile_toolchain_impl,
    attrs = {
        "available": attr.bool(default = False),
        "kicad_cli": attr.string(),
        "kicad_footprints": attr.string(),
        "python": attr.string(),
        "reason": attr.string(),
        "source": attr.string(),
        "version": attr.string(),
    },
    doc = "An atopile environment found on this machine (generated by repo.bzl).",
)
