"""Per-IC pin tables: atopile's symbolic lead -> pad number(s) -> net on the atopile board -> net on
each routed seed. Inputs: atopile/pinout/*.json and atopile/netlist/*.netlist.json.

usage: python3 pin_tables.py ATOPILE_DIR [REF ...]   (writes ATOPILE_DIR/pin-tables/<REF>.md and .csv)
"""

import csv
import glob
import json
import os
import sys


def pads_by_ref(netlist):
    out = {}
    for p in json.load(open(netlist))["pads"]:
        out[(p["ref"], str(p["pad"]))] = p.get("net") or ""
    return out


def main(root, refs):
    pinouts = {}
    for f in sorted(glob.glob(os.path.join(root, "pinout", "*.json"))):
        d = json.load(open(f))
        pinouts[d["designator"]] = (os.path.basename(f), d)
    routed = sorted(glob.glob(os.path.join(root, "netlist", "routed-s*.netlist.json")))
    seeds = [os.path.basename(r).split(".")[0].replace("routed-", "") for r in routed]
    nets = [pads_by_ref(r) for r in routed]
    ato = pads_by_ref(os.path.join(root, "netlist", "rev-a.netlist.json"))
    outdir = os.path.join(root, "pin-tables")
    os.makedirs(outdir, exist_ok=True)
    index = []
    for ref in refs:
        if ref not in pinouts:
            index.append(f"| {ref} | (no atopile pinout) | | |")
            continue
        src, d = pinouts[ref]
        rows = []
        for lead in d["leads"]:
            for pad in lead["padNumbers"] or [""]:
                row = [
                    lead["leadDesignator"],
                    pad,
                    lead.get("netName") or "",
                    ato.get((ref, pad), ""),
                ]
                row += [n.get((ref, pad), "") for n in nets]
                rows.append(row)
        hdr = ["symbolic lead", "pad/ball", "net (atopile pinout)", "net (atopile board)"] + [
            f"net (routed {s})" for s in seeds
        ]
        with open(os.path.join(outdir, f"{ref}.csv"), "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(hdr)
            w.writerows(rows)
        mism = sum(1 for r in rows if r[2] and any(x and x != r[2] for x in r[3:]))
        with open(os.path.join(outdir, f"{ref}.md"), "w") as f:
            f.write("<!-- markdownlint-disable -->\n\n")
            f.write(
                f"# {ref}: {d.get('typeName', '').split('::')[-1]} ({d.get('atoAddress', '')})\n\n"
            )
            f.write(
                f"Source: `pinout/{src}`. Rows: {len(rows)}. "
                f"Rows where a board net differs from the atopile pinout's net: {mism}.\n\n"
            )
            f.write("| " + " | ".join(hdr) + " |\n|" + "---|" * len(hdr) + "\n")
            for r in rows:
                f.write("| " + " | ".join(x if x else "—" for x in r) + " |\n")
        index.append(f"| {ref} | `{src}` | {len(rows)} | {mism} |")
    with open(os.path.join(outdir, "INDEX.md"), "w") as f:
        f.write("<!-- markdownlint-disable -->\n\n")
        f.write(
            "# Pin tables\n\nSymbolic lead (atopile) -> pad/ball -> net, on the atopile board and on each routed seed. "
        )
        f.write(
            "Generated by `tools/pin_tables.py`.\n\n"
            "| Ref | Pinout file | Rows | Rows with a differing net |\n|---|---|---|---|\n"
        )
        f.write("\n".join(index) + "\n")


if __name__ == "__main__":
    main(
        sys.argv[1],
        sys.argv[2:]
        or ["U1", "U2", "U3", "U4", "U5", "U6", "J1", "J2", "J3", "Y1", "Q1", "D1", "D2", "D3"],
    )
