"""Expected S-parameters of every modelled stick at nominal parameters (design §9).

The files hold the reference-plane-to-reference-plane response (what the multiline-TRL-
corrected measurement shows), renormalized from the TRL family's Zc to 50 Ω for comparison.
Launch and connector are not included: they are removed by the calibration, and the launch is
not 3D-modelled yet (design §6.2).
"""

from __future__ import annotations

import os
from typing import Dict, Optional

import numpy as np

from yapnr.rf.coupons import catalog, models, stackups, touchstone

GRID = np.arange(1, 181) * 100e6  # 0.1 to 18 GHz in 100 MHz steps (design §1.2: 0.1-18 GHz)


def stick_s(model: models.Model, b: catalog.Board, s: catalog.Stick) -> np.ndarray:
    ref = model.line(b.trl[s.trl]["family"]).zc
    return models.structure_s(model, s.elements, ref)


def write(
    stackup_id: str, out_dir: str, f: Optional[np.ndarray] = None, values=None
) -> Dict[str, str]:
    f = GRID if f is None else f
    st = stackups.get(stackup_id)
    v = stackups.with_values(st, values or {})
    model = models.Model(stackup_id, v, f)
    b = catalog.tune(catalog.board(stackup_id), model)
    os.makedirs(out_dir, exist_ok=True)
    out = {}
    for s in b.sticks:
        if not s.generated or s.ports != 2 or s.kind == "reflect":
            continue
        if s.kind == "thru":
            continue  # zero length between the reference planes: S = [[0, 1], [1, 0]]
        ref = model.line(b.trl[s.trl]["family"]).zc
        s50 = models.renormalize(stick_s(model, b, s), ref, 50.0)
        name = f"{s.id}-{s.family.replace('-', '')}-{s.kind}.s2p"
        path = os.path.join(out_dir, name)
        touchstone.write(
            path,
            f,
            s50,
            [
                f"yapnr rf coupon {b.letter}: {s.label} ({s.kind}, family {s.family})",
                f"stackup {stackup_id}, nominal parameters; reference planes {s.rp[0]:g} mm from"
                " each end; 50 ohm (renormalized from the line's Zc)",
                "model: 2D quasi-static RLGC (Djordjevic-Sarkar, Huray roughness, Wheeler loss);"
                " generated by python -m yapnr.rf.coupons expected",
            ],
            fmt="db",
            digits=4,
        )
        out[s.id] = path
    return out
