"""Board generation, KiCad DRC and the fab package (design §5.5, §5.6, §11.2).

`generate()` writes the KiCad project of one coupon board (board, project with the design rules,
custom rules, catalogue), then, when a headless kicad-cli is configured (YAPNR_KICAD_CLI), runs
DRC with the zones refilled, exports Gerbers and drill files from the filled copy and packs them
with the fab notes into `fab/<board>-fab.zip`. Every kicad-cli call is time-bounded. The board
file in the project stays unfilled (KiCad fills on DRC, plot and open), which keeps it small.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import zipfile
from typing import Dict, List, Optional

from yapnr.rf.coupons import catalog, families, layout, models, stackups

KICAD_CLI_ENV = ("YAPNR_KICAD_CLI", "PNR_KICAD_CLI")
TIMEOUT_S = 600


def kicad_cli() -> Optional[str]:
    for k in KICAD_CLI_ENV:
        p = os.environ.get(k)
        if p and os.access(p, os.X_OK):
            return p
    return None


def _run(cmd: List[str], cwd: str) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=TIMEOUT_S)


def tuned_board(stackup_id: str, upload: str = "") -> catalog.Board:
    st = stackups.get(stackup_id)
    from yapnr.rf.coupons import expected

    m = models.Model(stackup_id, stackups.with_values(st, {}), expected.GRID)
    b = catalog.board(stackup_id, upload)
    if st.board == "O":
        return catalog.tune_o(b, m)
    return catalog.tune(b, m)


def git_describe() -> str:
    """The generator's commit, short hash (with -dirty when the tree has changes)."""
    here = os.path.dirname(os.path.abspath(__file__))
    try:
        r = subprocess.run(
            ["git", "describe", "--always", "--dirty", "--abbrev=8"],
            cwd=here,
            capture_output=True,
            text=True,
            timeout=20,
        )
        return r.stdout.strip() or "unknown"
    except (OSError, subprocess.SubprocessError):
        return "unknown"


def tag_info(b: catalog.Board, revision: str, git: Optional[str] = None) -> Dict[str, str]:
    """The tag stick's text (board O): design §6."""
    st = stackups.get(b.stackup)
    designs = {"M": "R1 here; D1 on O0-D; D2 on O0-W", "W": "R1t, D2", "D": "D1, R1"}
    return dict(
        title=f"yapnr Order 0 rev {revision} {b.name}",
        stackup=st.id.lower(),
        git=f"gen {git or git_describe()}",
        designs=designs.get(b.upload, ""),
    )


def drc_summary(report: dict) -> dict:
    by = {}
    for v in report.get("violations", []):
        key = f"{v['severity']}:{v['type']}"
        by[key] = by.get(key, 0) + 1
    items = [
        dict(
            type=v["type"],
            severity=v["severity"],
            description=v["description"],
            items=[i["description"] for i in v.get("items", [])],
        )
        for v in report.get("violations", [])
    ]
    return dict(
        kicad_version=report.get("kicad_version", ""),
        violations=by,
        unconnected=len(report.get("unconnected_items", [])),
        details=items[:50],
    )


def fab_notes(b: catalog.Board, panel: layout.Panel, drc: Optional[dict]) -> str:
    st = stackups.get(b.stackup)
    n_cu = len(st.copper)
    fams = families.of(b.stackup)
    P = fams["P"]
    S = fams.get("S")
    lines = [
        f"# yapnr RF coupon board {b.letter}: fab notes",
        "",
        "Generated by `python -m yapnr.rf.coupons generate`; design: docs/design/rf-fab-coupons.md.",
        "Order the coupons exactly as the product will be ordered (design §5.6).",
        "",
        "| Option | Value |",
        "| --- | --- |",
        f"| Layers, thickness | {n_cu}, {st.thickness_mm:.2f} mm nominal (1.6 mm class) |",
        f"| Impedance control | yes, stackup {st.id} |",
        "| Impedance tolerance | the product's (±10 % standard) |",
        "| Copper | 1 oz outer, 0.5 oz inner |",
        f"| Finish | {st.finish} |",
        "| Mask, silkscreen | the product's colours |",
        "| Vias | 0.3 mm drill, 0.5 mm pad; tented"
        + ("; filled and capped (6-layer default)" if n_cu == 6 else "")
        + " |",
        f"| Panel | customer panel {panel.width:.1f} x {panel.height:.1f} mm, milled slots, mouse bites |",
        "| Quantity | 5 (measure at least 3) |",
        "| Order number | at the 'JLCJLCJLCJLC' text on the frame (specify location) |",
        "",
        "Controlled-impedance traces (do not change these widths; record any engineering query that"
        " does, since the width is an input of the fit):",
        "",
        f"- P: L1 grounded coplanar, {P.w:.3f} mm with {P.gap:.2f} mm gaps, under mask, 50 ohm.",
    ]
    if b.letter == "B":
        lines.append(f"- S: L3 stripline, {S.w:.3f} mm between L2 and L4, 50 ohm.")
    else:
        M = fams["M"]
        lines.append(f"- M: L1 microstrip, {M.w:.3f} mm, under mask, 50 ohm.")
    lines.append(
        "- every other trace and gap on the board (the 0.7x and 1.4x width variants, the coupled"
        " pair, the ring and stubs) is a test structure as well: no width or gap may be changed."
    )
    lines += [
        "",
        "Intentional features:",
        "",
        "- solder-mask openings over the mask-off test lines (MO_* footprints; the board's"
        " .kicad_dru allows only those to bridge the line and its ground);",
        "- planes cut out under the SMA pads and tapers (launch, design §6.2);",
        "- per-stick nets (GND_<stick>, RF_<stick>): sticks are electrically separate after break-out.",
        "",
        "Unverified (check before ordering): the edge SMA geometry (Samtec SMA-J-P-H-ST-EM1 pads from"
        " the KiCad library, in place of the design's Cinch 142-0701-851); whether break-out sticks"
        " cost extra; the launch is 2D-matched, not 3D-tuned.",
        "",
        "Checked against JLC's capabilities page (read 2026-10-02): copper at least 0.2 mm from a"
        " routed edge (the zones stop 0.30 mm from every edge; the DRC checks 0.25 mm); mouse-bite"
        " tabs at least 5 mm wide with 0.5-0.8 mm bites (5 mm, 0.5 mm at 0.8 mm pitch); silkscreen"
        " text 1.0 mm high, 0.15 mm lines.",
    ]
    if st.notes:
        lines += [""] + [f"- {n}" for n in st.notes]
    if drc is not None:
        lines += ["", "KiCad DRC (zones refilled):", ""]
        if drc["violations"]:
            lines += [f"- {k}: {n}" for k, n in sorted(drc["violations"].items())]
        else:
            lines.append("- no violations")
        lines.append(f"- unconnected items: {drc['unconnected']}")
    lines += [
        "",
        "Sticks:",
        "",
        "| Stick | Kind | Family | Length x width (mm) | Determines |",
        "| --- | --- | --- | --- | --- |",
    ]
    for pl in panel.placed:
        s = pl.stick
        lines.append(
            f"| {s.id} | {s.kind} | {s.family or '-'} | {s.length:g} x {s.height:g} | {s.determines} |"
        )
    return "\n".join(lines) + "\n"


def generate(
    stackup_id: str,
    out_dir: str,
    revision: str = "1",
    fab: bool = True,
    upload: str = "",
    git: Optional[str] = None,
) -> Dict[str, object]:
    """Write a coupon board's KiCad project (board O: one upload) and, with a headless
    kicad-cli, its DRC; JLC boards also get their Gerbers and fab notes (board O's fab staging
    goes through `yapnr fab build` instead)."""
    st = stackups.get(stackup_id)
    b = tuned_board(stackup_id, upload)
    osh = b.panel == "osh"
    if osh and revision == "1":
        revision = catalog.O_REV
    name = b.name
    os.makedirs(out_dir, exist_ok=True)
    info = tag_info(b, revision, git) if osh else None
    text, panel = layout.board_text(stackup_id, b, revision, info)
    pcb = os.path.join(out_dir, f"{name}.kicad_pcb")
    with open(pcb, "w", encoding="utf-8") as f:
        f.write(text)
    rules = layout.RULES_OSHPARK_4L if osh else None
    with open(os.path.join(out_dir, f"{name}.kicad_pro"), "w", encoding="utf-8") as f:
        json.dump(layout.project_json(name, rules), f, indent=2)
        f.write("\n")
    with open(os.path.join(out_dir, f"{name}.kicad_dru"), "w", encoding="utf-8") as f:
        f.write(layout.dru_text(panel.mask_rules, bites=osh))
    cat = b.to_json()
    heights = {pl.stick.id: pl.stick.height for pl in panel.placed}
    for s in cat["sticks"]:
        if s["id"] in heights:
            s["height"] = heights[s["id"]]
    cat["panel_mm"] = [round(panel.width, 2), round(panel.height, 2)]
    if osh:
        cat["panel_sq_in"] = round(panel.width * panel.height / 645.16, 2)
        cat["revision"] = revision
        cat["placement"] = {
            it.stick.id: dict(
                x=round(it.x - layout.ORIGIN[0], 3), y=round(it.y - layout.ORIGIN[1], 3), rot=it.rot
            )
            for it in panel.items
        }
        cat["tabs"] = len(panel.tabs)
    with open(os.path.join(out_dir, "catalog.json"), "w", encoding="utf-8") as f:
        json.dump(cat, f, indent=2)
        f.write("\n")
    out: Dict[str, object] = dict(board=pcb, panel=(panel.width, panel.height), drc=None)
    cli = kicad_cli()
    if not (fab and cli):
        return out
    if osh:
        drc = run_drc(cli, out_dir, name)
        out["drc"] = drc
        with open(os.path.join(out_dir, "drc-summary.json"), "w", encoding="utf-8") as f:
            json.dump(drc, f, indent=2)
            f.write("\n")
        return out
    with tempfile.TemporaryDirectory() as tmp:
        for ext in ("kicad_pcb", "kicad_pro", "kicad_dru"):
            shutil.copy(os.path.join(out_dir, f"{name}.{ext}"), tmp)
        rep = os.path.join(tmp, "drc.json")
        r = _run(
            [
                cli,
                "pcb",
                "drc",
                "--refill-zones",
                "--save-board",
                "--format",
                "json",
                "--severity-all",
                "-o",
                rep,
                f"{name}.kicad_pcb",
            ],
            tmp,
        )
        if not os.path.exists(rep):
            raise RuntimeError(f"kicad-cli drc failed: {r.stderr[-2000:]}")
        with open(rep, encoding="utf-8") as f:
            drc = drc_summary(json.load(f))
        out["drc"] = drc
        with open(os.path.join(out_dir, "drc-summary.json"), "w", encoding="utf-8") as f:
            json.dump(drc, f, indent=2)
            f.write("\n")
        gdir = os.path.join(tmp, "gerbers")
        os.makedirs(gdir)
        layers = [st.kicad_layer(i) for i in range(1, len(st.copper) + 1)]
        layers += ["F.Mask", "B.Mask", "F.SilkS", "B.SilkS", "Edge.Cuts"]
        _run(
            [
                cli,
                "pcb",
                "export",
                "gerbers",
                "-o",
                gdir + os.sep,
                "-l",
                ",".join(layers),
                "--no-netlist",
                f"{name}.kicad_pcb",
            ],
            tmp,
        ).check_returncode()
        _run(
            [
                cli,
                "pcb",
                "export",
                "drill",
                "-o",
                gdir + os.sep,
                "--format",
                "excellon",
                "--excellon-separate-th",
                f"{name}.kicad_pcb",
            ],
            tmp,
        ).check_returncode()
        notes = fab_notes(b, panel, drc)
        fab_dir = os.path.join(out_dir, "fab")
        os.makedirs(fab_dir, exist_ok=True)
        with open(os.path.join(fab_dir, "fab-notes.md"), "w", encoding="utf-8") as f:
            f.write(notes)
        zpath = os.path.join(fab_dir, f"{name}-fab.zip")
        with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
            for fn in sorted(os.listdir(gdir)):
                zi = zipfile.ZipInfo(f"{name}/{fn}", date_time=(2026, 1, 1, 0, 0, 0))
                zi.compress_type = zipfile.ZIP_DEFLATED
                with open(os.path.join(gdir, fn), "rb") as fh:
                    z.writestr(zi, _strip_dates(fn, fh.read()))
            zi = zipfile.ZipInfo(f"{name}/fab-notes.md", date_time=(2026, 1, 1, 0, 0, 0))
            zi.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(zi, notes.encode())
        out["fab_zip"] = zpath
    return out


def run_drc(cli: str, out_dir: str, name: str) -> dict:
    """KiCad's DRC with the zones refilled, on a copy of the project in `out_dir`."""
    with tempfile.TemporaryDirectory() as tmp:
        for ext in ("kicad_pcb", "kicad_pro", "kicad_dru"):
            shutil.copy(os.path.join(out_dir, f"{name}.{ext}"), tmp)
        rep = os.path.join(tmp, "drc.json")
        r = _run(
            [
                cli,
                "pcb",
                "drc",
                "--refill-zones",
                "--format",
                "json",
                "--severity-all",
                "-o",
                rep,
                f"{name}.kicad_pcb",
            ],
            tmp,
        )
        if not os.path.exists(rep):
            raise RuntimeError(f"kicad-cli drc failed: {r.stderr[-2000:]}")
        with open(rep, encoding="utf-8") as f:
            return drc_summary(json.load(f))


def generate_launch_check(region: str, out_dir: str, drc: bool = True) -> Dict[str, object]:
    """The launch check board of one Order 0 region (`catalog.launch_check_board`: a thru and
    a line stick with the Cinch 142-0701-851 launch), with the OSH Park 4-layer rules, and its
    KiCad DRC when a headless kicad-cli is configured."""
    b = catalog.launch_check_board(region)
    name = f"launch-{region}"
    os.makedirs(out_dir, exist_ok=True)
    text, panel = layout.board_text(b.stackup, b)
    pcb = os.path.join(out_dir, f"{name}.kicad_pcb")
    with open(pcb, "w", encoding="utf-8") as f:
        f.write(text)
    with open(os.path.join(out_dir, f"{name}.kicad_pro"), "w", encoding="utf-8") as f:
        json.dump(layout.project_json(name, layout.RULES_OSHPARK_4L), f, indent=2)
        f.write("\n")
    with open(os.path.join(out_dir, f"{name}.kicad_dru"), "w", encoding="utf-8") as f:
        f.write(layout.dru_text(panel.mask_rules))
    out: Dict[str, object] = dict(board=pcb, panel=(panel.width, panel.height), drc=None)
    cli = kicad_cli()
    if drc and cli:
        out["drc"] = run_drc(cli, out_dir, name)
    return out


def _strip_dates(name: str, data: bytes) -> bytes:
    """Drop the creation-date comments KiCad writes into Gerber, drill and job files, so the
    package is reproducible."""
    import re

    lines = data.split(b"\n")
    keep = [ln for ln in lines if b"CreationDate" not in ln]
    # "G04 Created by KiCad (PCBNEW 10.0.6) date 2026-...", "; DRILL file {KiCad 10.0.6} date ..."
    keep = [re.sub(rb" date \d{4}-\d\d-\d\d[ T][0-9:]+", b"", ln) for ln in keep]
    return b"\n".join(keep)
